// <auto-generated />
using System;
using GlassFlowAyF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlassFlowAyF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808211447_ProductosMaterialesFotografias")]
    partial class ProductosMaterialesFotografias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GlassFlowAyF.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GlassFlowAyF.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acabado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Color")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Grosor")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Perfil")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Materiales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acabado = "Brillante",
                            Activo = true,
                            Color = "Transparente",
                            Descripcion = "Vidrio templado transparente de alta resistencia.",
                            Grosor = 10m,
                            Nombre = "Vidrio templado transparente",
                            Perfil = "Aluminio negro",
                            PrecioAdicional = 0m,
                            Tipo = "Vidrio templado"
                        },
                        new
                        {
                            Id = 2,
                            Acabado = "Brillante",
                            Activo = true,
                            Color = "Bronce",
                            Descripcion = "Vidrio templado con tonalidad bronce.",
                            Grosor = 10m,
                            Nombre = "Vidrio templado bronce",
                            Perfil = "Aluminio negro",
                            PrecioAdicional = 25000m,
                            Tipo = "Vidrio templado"
                        },
                        new
                        {
                            Id = 3,
                            Acabado = "Natural",
                            Activo = true,
                            Color = "Transparente",
                            Descripcion = "Vidrio laminado con mayor seguridad.",
                            Grosor = 8m,
                            Nombre = "Vidrio laminado",
                            Perfil = "Aluminio natural",
                            PrecioAdicional = 35000m,
                            Tipo = "Vidrio laminado"
                        },
                        new
                        {
                            Id = 4,
                            Acabado = "Mate",
                            Activo = true,
                            Color = "Esmerilado",
                            Descripcion = "Vidrio con acabado de privacidad.",
                            Grosor = 8m,
                            Nombre = "Vidrio esmerilado",
                            Perfil = "Aluminio negro",
                            PrecioAdicional = 30000m,
                            Tipo = "Vidrio templado"
                        });
                });

            modelBuilder.Entity("GlassFlowAyF.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("PermiteInstalacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Puertas",
                            Descripcion = "Puerta corrediza en vidrio templado.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Puerta de baño corrediza",
                            PermiteInstalacion = true,
                            PrecioBase = 350000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Ventanas",
                            Descripcion = "Ventana personalizada en aluminio y vidrio.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ventana en vidrio",
                            PermiteInstalacion = true,
                            PrecioBase = 180000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Espejos",
                            Descripcion = "Espejo fabricado según las medidas del cliente.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Espejo personalizado",
                            PermiteInstalacion = true,
                            PrecioBase = 95000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "Estructuras",
                            Descripcion = "Estructura personalizada para interiores.",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Estructura en vidrio",
                            PermiteInstalacion = true,
                            PrecioBase = 420000m
                        });
                });

            modelBuilder.Entity("GlassFlowAyF.Models.ProductoMaterial", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("ProductoId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ProductoMateriales");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductoId = 1,
                            MaterialId = 2
                        },
                        new
                        {
                            ProductoId = 1,
                            MaterialId = 4
                        },
                        new
                        {
                            ProductoId = 2,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductoId = 2,
                            MaterialId = 2
                        },
                        new
                        {
                            ProductoId = 2,
                            MaterialId = 3
                        },
                        new
                        {
                            ProductoId = 3,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductoId = 3,
                            MaterialId = 4
                        },
                        new
                        {
                            ProductoId = 4,
                            MaterialId = 1
                        },
                        new
                        {
                            ProductoId = 4,
                            MaterialId = 3
                        });
                });

            modelBuilder.Entity("GlassFlowAyF.Models.SolicitudCotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Alto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Ancho")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoEstimado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Profundidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RequiereInstalacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductoId");

                    b.ToTable("SolicitudesCotizacion");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.SolicitudFotografia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SolicitudCotizacionId")
                        .HasColumnType("int");

                    b.Property<string>("TipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudCotizacionId");

                    b.ToTable("SolicitudFotografias");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.TrabajoInstalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaInstalacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("InstalacionRealizada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Instalador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("LimpiezaFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MaterialListo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MedidasConfirmadas")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("RevisionAcabados")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TrabajosInstalacion");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.VisitaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SolicitudCotizacionId")
                        .HasColumnType("int");

                    b.Property<string>("TecnicoAsignado")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudCotizacionId");

                    b.ToTable("VisitasTecnicas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GlassFlowAyF.Models.ProductoMaterial", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.Material", "Material")
                        .WithMany("ProductoMateriales")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlassFlowAyF.Models.Producto", "Producto")
                        .WithMany("ProductoMateriales")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.SolicitudCotizacion", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.Material", "Material")
                        .WithMany("Solicitudes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlassFlowAyF.Models.Producto", "Producto")
                        .WithMany("Solicitudes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.SolicitudFotografia", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.SolicitudCotizacion", "SolicitudCotizacion")
                        .WithMany("Fotografias")
                        .HasForeignKey("SolicitudCotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudCotizacion");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.VisitaTecnica", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.SolicitudCotizacion", "SolicitudCotizacion")
                        .WithMany()
                        .HasForeignKey("SolicitudCotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudCotizacion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlassFlowAyF.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GlassFlowAyF.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlassFlowAyF.Models.Material", b =>
                {
                    b.Navigation("ProductoMateriales");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.Producto", b =>
                {
                    b.Navigation("ProductoMateriales");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("GlassFlowAyF.Models.SolicitudCotizacion", b =>
                {
                    b.Navigation("Fotografias");
                });
#pragma warning restore 612, 618
        }
    }
}
